version: "3"

services:
  app:
    build: .
    image: orange-vanguard-dev
    command: "npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "node_modules:/app/node_modules"
      - "next:/app/.next"
    environment:
      NODE_ENV: development

volumes:
  node_modules:
  next:
